// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/install": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/subclient-login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/install" | "/login" | "/subclient-login";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/install.tsx": {
    id: "routes/install";
    page: "/install";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/subclient-login.tsx": {
    id: "routes/subclient-login";
    page: "/subclient-login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/install": typeof import("./app/routes/install.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/subclient-login": typeof import("./app/routes/subclient-login.tsx");
};