// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type EmbedCss struct {
	ProjectID string    `json:"project_id"`
	CustomCss string    `json:"custom_css"`
	UpdatedAt time.Time `json:"updated_at"`
}

type License struct {
	ID                   string    `json:"id"`
	LicenseKey           string    `json:"license_key"`
	TenantName           string    `json:"tenant_name"`
	MaxProjectsPerTenant int64     `json:"max_projects_per_tenant"`
	WhatsappEnabled      int64     `json:"whatsapp_enabled"`
	SubclientEnabled     int64     `json:"subclient_enabled"`
	CreatedAt            time.Time `json:"created_at"`
}

type Project struct {
	ID               string         `json:"id"`
	TenantID         string         `json:"tenant_id"`
	Name             string         `json:"name"`
	WhatsappEnabled  int64          `json:"whatsapp_enabled"`
	SubclientEnabled int64          `json:"subclient_enabled"`
	CreatedByUserID  string         `json:"created_by_user_id"`
	CreatedAt        time.Time      `json:"created_at"`
	ShowHistory      int64          `json:"show_history"`
	UseClientUid     int64          `json:"use_client_uid"`
	AllowedOrigins   sql.NullString `json:"allowed_origins"`
}

type Session struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	ScopeType string         `json:"scope_type"`
	ScopeID   string         `json:"scope_id"`
	TokenHash string         `json:"token_hash"`
	Host      sql.NullString `json:"host"`
	ExpiresAt time.Time      `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type Subclient struct {
	ID              string    `json:"id"`
	ProjectID       string    `json:"project_id"`
	Name            string    `json:"name"`
	Domain          string    `json:"domain"`
	CreatedByUserID string    `json:"created_by_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Tenant struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Domain    string    `json:"domain"`
	IsDefault int64     `json:"is_default"`
	CreatedAt time.Time `json:"created_at"`
	HasLogo   int64     `json:"has_logo"`
	UpdatedAt int64     `json:"updated_at"`
}

type User struct {
	ID           string         `json:"id"`
	TenantID     sql.NullString `json:"tenant_id"`
	ProjectID    sql.NullString `json:"project_id"`
	SubclientID  sql.NullString `json:"subclient_id"`
	Username     string         `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         string         `json:"role"`
	Source       string         `json:"source"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	Email        sql.NullString `json:"email"`
}
