// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountLicenses(ctx context.Context) (int64, error)
	CountProjectsForTenant(ctx context.Context, tenantID string) (int64, error)
	DeleteSession(ctx context.Context, tokenHash string) error
	GetDefaultTenant(ctx context.Context) (string, error)
	GetLicense(ctx context.Context) (GetLicenseRow, error)
	GetProjectByTenant(ctx context.Context, arg GetProjectByTenantParams) (GetProjectByTenantRow, error)
	GetSession(ctx context.Context, tokenHash string) (GetSessionRow, error)
	GetSubclientByDomain(ctx context.Context, domain string) (GetSubclientByDomainRow, error)
	GetSubclientByID(ctx context.Context, id string) (string, error)
	GetSubclientFullByID(ctx context.Context, id string) (GetSubclientFullByIDRow, error)
	GetSubclientUser(ctx context.Context, arg GetSubclientUserParams) (GetSubclientUserRow, error)
	GetTenantByDomain(ctx context.Context, domain string) (string, error)
	GetTenantByID(ctx context.Context, id string) (string, error)
	GetTenantUser(ctx context.Context, arg GetTenantUserParams) (GetTenantUserRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	InsertLicense(ctx context.Context, arg InsertLicenseParams) error
	InsertProject(ctx context.Context, arg InsertProjectParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertSubclient(ctx context.Context, arg InsertSubclientParams) error
	InsertTenant(ctx context.Context, arg InsertTenantParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	ListProjects(ctx context.Context, tenantID string) ([]Project, error)
	ListSubclients(ctx context.Context, projectID string) ([]ListSubclientsRow, error)
	UpsertWhatsappUser(ctx context.Context, arg UpsertWhatsappUserParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
}

var _ Querier = (*Queries)(nil)
